/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import classesbasicas.Login;
import classesbasicas.Proprietario;
import classesbasicas.Registro;
import classesexception.ProprietarioException;
import classesexception.RegistroException;
import classesfachada.Fachada;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import util.Datas;

/**
 *
 * @author SONY VAIO
 */
public class TelaNovoAlterarProprietario extends javax.swing.JFrame {

    /**
     * Creates new form NovoAlterarLocador
     */
       Date datareg = Datas.obterTimestampAtual();
        String dataRegT = Datas.formatarData(datareg, "dd/MM/yyyy");
    Proprietario proSelecionado = new Proprietario();
    Login login;
    //<editor-fold defaultstate="collapsed" desc="Construtores da tela">
    public TelaNovoAlterarProprietario(Login l) {
        initComponents();
        this.login = l;
        this.jButtonAlterar.setEnabled(false);
        this.jLabel2.setVisible(false);
        this.jComboBox1SituacaoLocador.setVisible(false);
    }

   
    public TelaNovoAlterarProprietario(Proprietario p, Login l) {
        initComponents();
        this.proSelecionado = p;
        this.login = l;
        jTextFieldNome.setText(p.getNome());
        jTextFieldFone.setText(p.getTelefone());
        jTextFieldFoneComercial.setText(p.getTelefone2());
        jTextFieldCelular.setText(p.getTelefone3());
        jTextFieldEmail.setText(p.getEmail());
        jComboBox1SituacaoLocador.setSelectedItem(p.getSituacao());
        jButtonSalvar.setEnabled(false);
    }
    public TelaNovoAlterarProprietario(){
        
    }
//</editor-fold>

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAlterar = new javax.swing.JButton();
        jButtonretornar = new javax.swing.JButton();
        jPanelDadosLocador = new javax.swing.JPanel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldFone = new javax.swing.JTextField();
        jTextFieldFoneComercial = new javax.swing.JTextField();
        jTextFieldCelular = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelNome = new javax.swing.JLabel();
        jLabelFone = new javax.swing.JLabel();
        jLabelFoneComercial = new javax.swing.JLabel();
        jLabelCelular = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1SituacaoLocador = new javax.swing.JComboBox();
        jButtonSalvar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonretornar.setText("Retornar");
        jButtonretornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonretornarActionPerformed(evt);
            }
        });

        jPanelDadosLocador.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Proprietário"));

        jLabelNome.setText("* Nome:");

        jLabelFone.setText("* Fone:");

        jLabelFoneComercial.setText("Fone comercial:");

        jLabelCelular.setText("Celular:");

        jLabelEmail.setText("* E-Mail:");

        jLabel2.setText("Situação:");

        jComboBox1SituacaoLocador.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ATIVO", "INATIVO" }));

        javax.swing.GroupLayout jPanelDadosLocadorLayout = new javax.swing.GroupLayout(jPanelDadosLocador);
        jPanelDadosLocador.setLayout(jPanelDadosLocadorLayout);
        jPanelDadosLocadorLayout.setHorizontalGroup(
            jPanelDadosLocadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosLocadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosLocadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFone)
                    .addComponent(jLabelFoneComercial)
                    .addComponent(jLabelEmail)
                    .addComponent(jLabelNome)
                    .addComponent(jLabelCelular)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanelDadosLocadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1SituacaoLocador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelDadosLocadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldFone, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldFoneComercial, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldCelular, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDadosLocadorLayout.setVerticalGroup(
            jPanelDadosLocadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosLocadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosLocadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosLocadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFone)
                    .addComponent(jTextFieldFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosLocadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFoneComercial)
                    .addComponent(jTextFieldFoneComercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosLocadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCelular)
                    .addComponent(jTextFieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosLocadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDadosLocadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1SituacaoLocador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/barra2.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDadosLocador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonretornar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 662, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAlterar)
                        .addGap(96, 96, 96)
                        .addComponent(jButtonretornar))
                    .addComponent(jPanelDadosLocador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void limparCamposDepoisDeSalvar() {
        jTextFieldNome.setText(null);
        jTextFieldFone.setText(null);
        jTextFieldFoneComercial.setText(null);
        jTextFieldCelular.setText(null);
        jTextFieldEmail.setText(null);

        //jButtonAlterar.setEnabled(false);
    }

    public void limparCamposDepoisDeAlterar() {
        jTextFieldNome.setText(null);
        jTextFieldFone.setText(null);
        jTextFieldFoneComercial.setText(null);
        jTextFieldCelular.setText(null);
        jTextFieldEmail.setText(null);

        jButtonAlterar.setEnabled(false);
    }


    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:
        try {
            Fachada fachada = new Fachada();
            Proprietario p = new Proprietario();
            p.setNome(jTextFieldNome.getText());
            p.setTelefone(jTextFieldFone.getText());
            p.setTelefone2(jTextFieldFoneComercial.getText());
            p.setTelefone3(jTextFieldCelular.getText());
            p.setEmail(jTextFieldEmail.getText());
            
            if (jComboBox1SituacaoLocador.getSelectedItem().toString().equalsIgnoreCase("ATIVO")) {
                p.setSituacao("ATIVO");

            } else {
                p.setSituacao("INATIVO");
            }
            
            fachada.saveProprietario(p);
            Registro r = new Registro();
            r.setLogin(login);
            r.setDescricao("Salvou Proprietario: "+p.getNome());
            r.setDataregistro(datareg);
            fachada.saveRegistro(r);
            this.limparCamposDepoisDeSalvar();
             JOptionPane.showMessageDialog(rootPane, "Proprietário Salvo com sucesso!");
        } catch (ProprietarioException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }  catch (RegistroException ex) {
               Logger.getLogger(TelaNovoAlterarProprietario.class.getName()).log(Level.SEVERE, null, ex);
           }
       
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        // TODO add your handling code here:
        try {
            Fachada f = new Fachada();
            proSelecionado = f.findProprietario(proSelecionado);

            proSelecionado.setNome(jTextFieldNome.getText());
            proSelecionado.setTelefone(jTextFieldFone.getText());
            proSelecionado.setTelefone2(jTextFieldFoneComercial.getText());
            proSelecionado.setTelefone3(jTextFieldCelular.getText());
            proSelecionado.setEmail(jTextFieldEmail.getText());

            if (jComboBox1SituacaoLocador.getSelectedItem().toString().equalsIgnoreCase("ATIVO")) {
                proSelecionado.setSituacao("ATIVO");

            } else {
                proSelecionado.setSituacao("INATIVO");
            }
            
            f.saveProprietario(proSelecionado);
                 Registro r = new Registro();
            r.setLogin(login);
            r.setDescricao("Alterou Proprietario: "+proSelecionado.getNome());
            r.setDataregistro(datareg);
            f.saveRegistro(r);
            this.limparCamposDepoisDeAlterar();
            JOptionPane.showMessageDialog(rootPane, "Proprietario Alterado com sucesso!");
        } catch (ProprietarioException ex) {
            Logger.getLogger(TelaNovoAlterarApt.class.getName()).log(Level.SEVERE, null, ex);
        }  catch (RegistroException ex) {
               Logger.getLogger(TelaNovoAlterarProprietario.class.getName()).log(Level.SEVERE, null, ex);
           }
        
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonretornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonretornarActionPerformed
        // TODO add your handling code here:
       TelaGerenciaProprietario tgp = new TelaGerenciaProprietario(login);

        tgp.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_jButtonretornarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaNovoAlterarProprietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaNovoAlterarProprietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaNovoAlterarProprietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaNovoAlterarProprietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaNovoAlterarProprietario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonretornar;
    private javax.swing.JComboBox jComboBox1SituacaoLocador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCelular;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelFone;
    private javax.swing.JLabel jLabelFoneComercial;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JPanel jPanelDadosLocador;
    private javax.swing.JTextField jTextFieldCelular;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFone;
    private javax.swing.JTextField jTextFieldFoneComercial;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
