/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import classesbasicas.Apartamento;
import classesbasicas.CheckIn;
import classesbasicas.Locatario;
import classesexception.CheckInException;
import classesfachada.Fachada;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import util.Datas;

/**
 *
 * @author mimmo
 */
public class TelaGerenciaCheckIn extends javax.swing.JFrame {

    /**
     * Creates new form CadastroImovel
     */
    TelaPainelPrincipal tpp;
    ArrayList<Locatario> listaLocatario;
    ArrayList<Apartamento> listaApartamento;
    Locatario cpfSelecionado;
    Apartamento aptSelecionado;

    public TelaGerenciaCheckIn(TelaPainelPrincipal tpp) {
        initComponents();
        carregarComboApt();
        carregarComboCpfLocatario();
        this.tpp = tpp;

        //data de Entrada
        Date datareg;
        datareg = Datas.obterTimestampAtual();
        String dataRegT = Datas.formatarData(datareg, "dd/MM/yyyy");
        jTextField1DataDeRegistro.setText(dataRegT);
        jTextField1DataDeRegistro.setEnabled(false);

    }

    private TelaGerenciaCheckIn() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void carregarComboApt() {
        Fachada fachada = new Fachada();
        Apartamento apt = new Apartamento();

        listaApartamento = (ArrayList<Apartamento>) fachada.listallApartamento(apt);
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < listaApartamento.size(); i++) {
            modelo.addElement(listaApartamento.get(i).getNumero());
        }
        jComboBoxAptos.setModel(modelo);
    }

    private void carregarComboCpfLocatario() {
        Fachada fachada = new Fachada();
        Locatario locatario = new Locatario();

        listaLocatario = (ArrayList<Locatario>) fachada.listallLocatario(locatario);
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (int i = 0; i < listaLocatario.size(); i++) {
            modelo.addElement(listaLocatario.get(i).getCpg());
        }
        jComboBoxCPF.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupPossueCarros = new javax.swing.ButtonGroup();
        buttonGroup1leituraEntrada = new javax.swing.ButtonGroup();
        buttonGroup2leituraSaida = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jButtonRegistrarSaida = new javax.swing.JButton();
        jButtonRetornarPrincipal = new javax.swing.JButton();
        jPanelDados = new javax.swing.JPanel();
        jTextFieldValorTotal = new javax.swing.JTextField();
        jTextFieldValorDiaria = new javax.swing.JTextField();
        jTextFieldValorMensal = new javax.swing.JTextField();
        jLabelTotalKw = new javax.swing.JLabel();
        jLabel1Acompanhou = new javax.swing.JLabel();
        jLabelLeituraEntrada = new javax.swing.JLabel();
        jLabelLeituraSaida = new javax.swing.JLabel();
        jTextFieldLeituraSaida = new javax.swing.JTextField();
        jTextFieldTotalKw = new javax.swing.JTextField();
        jLabel2Acompanhou = new javax.swing.JLabel();
        jTextFieldLeituraEntrada = new javax.swing.JTextField();
        jLabelValorTotal = new javax.swing.JLabel();
        jLabelValorDiaria = new javax.swing.JLabel();
        jCheckBox3Nao = new javax.swing.JCheckBox();
        jCheckBox2Nao = new javax.swing.JCheckBox();
        jLabelValorMensal = new javax.swing.JLabel();
        jCheckBox2Sim = new javax.swing.JCheckBox();
        jCheckBox3Sim = new javax.swing.JCheckBox();
        jLabelFormaDePagamento = new javax.swing.JLabel();
        jComboBoxFormaDePagamento = new javax.swing.JComboBox();
        jTextFieldDataEntrada = new javax.swing.JTextField();
        jTextFieldDataSaida = new javax.swing.JTextField();
        jLabelDataEntrada = new javax.swing.JLabel();
        jLabelDataSaida = new javax.swing.JLabel();
        jLabel1DataRegistro = new javax.swing.JLabel();
        jTextField1DataDeRegistro = new javax.swing.JTextField();
        jPanel1DadosLocatario = new javax.swing.JPanel();
        jLabelEnderecoRes = new javax.swing.JLabel();
        jTextFieldEnderecoRes = new javax.swing.JTextField();
        jLabelFone = new javax.swing.JLabel();
        jTextFieldIdade = new javax.swing.JTextField();
        jTextFieldPassaport = new javax.swing.JTextField();
        jTextFieldMotivo = new javax.swing.JTextField();
        jTextFieldCelular = new javax.swing.JTextField();
        jTextFieldAptN = new javax.swing.JTextField();
        jLabelIdade = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelIdentidade = new javax.swing.JLabel();
        jLabelPassaport = new javax.swing.JLabel();
        jLabelProcedencia = new javax.swing.JLabel();
        jLabelAptN = new javax.swing.JLabel();
        jLabelCEP = new javax.swing.JLabel();
        jTextFieldIdentidade = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jLabelOrgExp = new javax.swing.JLabel();
        jTextFieldBairro = new javax.swing.JTextField();
        jTextFieldFone = new javax.swing.JTextField();
        jLabelCelular = new javax.swing.JLabel();
        jTextFieldProcedencia = new javax.swing.JTextField();
        jLabelMotivo = new javax.swing.JLabel();
        jTextFieldOrgExp = new javax.swing.JTextField();
        jTextFieldCEP = new javax.swing.JTextField();
        jLabelBairro = new javax.swing.JLabel();
        jLabelCPF = new javax.swing.JLabel();
        jComboBoxCPF = new javax.swing.JComboBox();
        jLabelEstCivil = new javax.swing.JLabel();
        jTextFieldEstCivil = new javax.swing.JTextField();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNomeCompleto = new javax.swing.JTextField();
        jTextFieldResponsavel = new javax.swing.JTextField();
        jLabelResponsavel = new javax.swing.JLabel();
        jPanel1Carro = new javax.swing.JPanel();
        jCheckBox1Sim = new javax.swing.JCheckBox();
        jCheckBox1Nao = new javax.swing.JCheckBox();
        jTextFieldCarroMarca = new javax.swing.JTextField();
        jTextFieldCor = new javax.swing.JTextField();
        jTextFieldPlacas = new javax.swing.JTextField();
        jLabelCarroMarca = new javax.swing.JLabel();
        jLabelCarro = new javax.swing.JLabel();
        jLabelPlacas = new javax.swing.JLabel();
        jLabelCor = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jComboBoxAptos = new javax.swing.JComboBox();
        jButtonCadastrarNovoCliente = new javax.swing.JButton();
        jLabelApto = new javax.swing.JLabel();
        jButtonregistrarEntrada = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1100, 1200));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1000, 650));

        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 800));

        jButtonRegistrarSaida.setText("Registrar Saída");

        jButtonRetornarPrincipal.setText("Retornar a Tela Principal");
        jButtonRetornarPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetornarPrincipalActionPerformed(evt);
            }
        });

        jPanelDados.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));

        jLabelTotalKw.setText("Total de Kw/h:");

        jLabel1Acompanhou.setText("Hóspede acompanhou a leitura?");

        jLabelLeituraEntrada.setText("Leitura de Entrada:");

        jLabelLeituraSaida.setText("Leitura de Saída:");

        jLabel2Acompanhou.setText("Hóspede acompanhou a leitura?");

        jLabelValorTotal.setText("Valor Total de Diárias:");

        jLabelValorDiaria.setText("Valor de 1(Uma) Diária:");

        buttonGroup2leituraSaida.add(jCheckBox3Nao);
        jCheckBox3Nao.setText("Não");

        buttonGroup1leituraEntrada.add(jCheckBox2Nao);
        jCheckBox2Nao.setText("Não");

        jLabelValorMensal.setText("Valor mensal do Alugue:");

        buttonGroup1leituraEntrada.add(jCheckBox2Sim);
        jCheckBox2Sim.setText("Sim");

        buttonGroup2leituraSaida.add(jCheckBox3Sim);
        jCheckBox3Sim.setText("Sim");

        jLabelFormaDePagamento.setText("Forma de Pagamento:");

        jComboBoxFormaDePagamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A Vista", "Cheque", "Cartão - Debito", "Cartão - Prazo" }));
        jComboBoxFormaDePagamento.setPreferredSize(new java.awt.Dimension(6, 20));

        jLabelDataEntrada.setText("Data Entrada / Arrival Date");

        jLabelDataSaida.setText("Data Saída / Leaving On:");

        jLabel1DataRegistro.setText("Data de Registro:");

        jTextField1DataDeRegistro.setEditable(false);
        jTextField1DataDeRegistro.setEnabled(false);

        javax.swing.GroupLayout jPanelDadosLayout = new javax.swing.GroupLayout(jPanelDados);
        jPanelDados.setLayout(jPanelDadosLayout);
        jPanelDadosLayout.setHorizontalGroup(
            jPanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDadosLayout.createSequentialGroup()
                        .addComponent(jLabelLeituraEntrada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldLeituraEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDadosLayout.createSequentialGroup()
                                .addComponent(jLabel2Acompanhou)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox3Sim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox3Nao))
                            .addGroup(jPanelDadosLayout.createSequentialGroup()
                                .addComponent(jLabelLeituraSaida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldLeituraSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelTotalKw)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldTotalKw))))
                    .addGroup(jPanelDadosLayout.createSequentialGroup()
                        .addComponent(jLabelValorMensal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldValorMensal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabelValorDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldValorDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelValorTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelFormaDePagamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxFormaDePagamento, 0, 148, Short.MAX_VALUE))
                    .addGroup(jPanelDadosLayout.createSequentialGroup()
                        .addComponent(jLabel1Acompanhou)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox2Sim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox2Nao)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelDadosLayout.createSequentialGroup()
                        .addComponent(jLabelDataEntrada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDataSaida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDataSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1DataRegistro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1DataDeRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelDadosLayout.setVerticalGroup(
            jPanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDataEntrada)
                    .addComponent(jTextFieldDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDataSaida)
                    .addComponent(jTextFieldDataSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1DataRegistro)
                    .addComponent(jTextField1DataDeRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelValorMensal)
                    .addComponent(jTextFieldValorMensal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelValorDiaria)
                    .addComponent(jTextFieldValorDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelValorTotal)
                    .addComponent(jTextFieldValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFormaDePagamento)
                    .addComponent(jComboBoxFormaDePagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLeituraEntrada)
                    .addComponent(jLabelLeituraSaida)
                    .addComponent(jLabelTotalKw)
                    .addComponent(jTextFieldLeituraEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLeituraSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTotalKw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1Acompanhou)
                    .addComponent(jLabel2Acompanhou)
                    .addComponent(jCheckBox2Sim)
                    .addComponent(jCheckBox3Sim)
                    .addComponent(jCheckBox2Nao)
                    .addComponent(jCheckBox3Nao))
                .addContainerGap())
        );

        jPanel1DadosLocatario.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Locatário"));

        jLabelEnderecoRes.setText("Endereço residencial/ Full adress:");

        jTextFieldEnderecoRes.setEnabled(false);

        jLabelFone.setText("Fone/ Phone:");

        jTextFieldIdade.setEnabled(false);

        jTextFieldPassaport.setEnabled(false);

        jTextFieldMotivo.setEnabled(false);

        jTextFieldCelular.setEnabled(false);

        jTextFieldAptN.setEnabled(false);

        jLabelIdade.setText("Idade / Age:");

        jTextFieldEmail.setEnabled(false);

        jLabelIdentidade.setText("Doc. Identidade / Identification");

        jLabelPassaport.setText("Passaport nº:");

        jLabelProcedencia.setText("Última Procedência (Cidade/ Estado/ Pais) / Arriving From (City/ Country)");

        jLabelAptN.setText("Aptº/ Nº:");

        jLabelCEP.setText("CEP:");

        jTextFieldIdentidade.setEnabled(false);

        jLabelEmail.setText("Endereço Eletrônico - Email (E-mail Address)");

        jLabelOrgExp.setText("Org. Exp.");

        jTextFieldBairro.setEnabled(false);

        jTextFieldFone.setEnabled(false);

        jLabelCelular.setText("Celular:");

        jTextFieldProcedencia.setEnabled(false);

        jLabelMotivo.setText("Motivo da Viagem / Porpose of Trip");

        jTextFieldOrgExp.setEnabled(false);

        jTextFieldCEP.setEnabled(false);

        jLabelBairro.setText("Bairro:");

        jLabelCPF.setText("CPF Nº");

        jComboBoxCPF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxCPF.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxCPFItemStateChanged(evt);
            }
        });

        jLabelEstCivil.setText("Est. Civil / Marital Status:");

        jTextFieldEstCivil.setEnabled(false);

        jLabelNome.setText("Nome Completo/ Full name:");

        jTextFieldNomeCompleto.setEnabled(false);

        jTextFieldResponsavel.setEnabled(false);

        jLabelResponsavel.setText("Responsável pelo Pagamento / Responsabile for payment:");

        javax.swing.GroupLayout jPanel1DadosLocatarioLayout = new javax.swing.GroupLayout(jPanel1DadosLocatario);
        jPanel1DadosLocatario.setLayout(jPanel1DadosLocatarioLayout);
        jPanel1DadosLocatarioLayout.setHorizontalGroup(
            jPanel1DadosLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1DadosLocatarioLayout.createSequentialGroup()
                .addComponent(jLabelAptN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldAptN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelBairro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCEP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1DadosLocatarioLayout.createSequentialGroup()
                .addGroup(jPanel1DadosLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1DadosLocatarioLayout.createSequentialGroup()
                        .addComponent(jLabelCPF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNomeCompleto))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1DadosLocatarioLayout.createSequentialGroup()
                        .addComponent(jLabelEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldEmail))
                    .addGroup(jPanel1DadosLocatarioLayout.createSequentialGroup()
                        .addComponent(jLabelResponsavel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldResponsavel))
                    .addGroup(jPanel1DadosLocatarioLayout.createSequentialGroup()
                        .addGroup(jPanel1DadosLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelProcedencia)
                            .addComponent(jTextFieldProcedencia, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1DadosLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1DadosLocatarioLayout.createSequentialGroup()
                                .addComponent(jLabelMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextFieldMotivo)))
                    .addGroup(jPanel1DadosLocatarioLayout.createSequentialGroup()
                        .addComponent(jLabelEnderecoRes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldEnderecoRes))
                    .addGroup(jPanel1DadosLocatarioLayout.createSequentialGroup()
                        .addGroup(jPanel1DadosLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1DadosLocatarioLayout.createSequentialGroup()
                                .addComponent(jLabelEstCivil)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldEstCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelFone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldFone, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelCelular)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelIdade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1DadosLocatarioLayout.createSequentialGroup()
                                .addComponent(jLabelIdentidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldIdentidade, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelOrgExp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldOrgExp, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelPassaport)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPassaport, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1DadosLocatarioLayout.setVerticalGroup(
            jPanel1DadosLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1DadosLocatarioLayout.createSequentialGroup()
                .addGroup(jPanel1DadosLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCPF)
                    .addComponent(jComboBoxCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1DadosLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEstCivil)
                    .addComponent(jTextFieldEstCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFone)
                    .addComponent(jTextFieldFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCelular)
                    .addComponent(jLabelIdade)
                    .addComponent(jTextFieldIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1DadosLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEnderecoRes)
                    .addComponent(jTextFieldEnderecoRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1DadosLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextFieldAptN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAptN)
                    .addGroup(jPanel1DadosLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelCEP)
                        .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelBairro)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1DadosLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProcedencia)
                    .addComponent(jLabelMotivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1DadosLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldProcedencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1DadosLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1DadosLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdentidade)
                    .addComponent(jTextFieldOrgExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOrgExp)
                    .addComponent(jTextFieldIdentidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPassaport)
                    .addComponent(jTextFieldPassaport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1DadosLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelResponsavel)
                    .addComponent(jTextFieldResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Carro.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados de Veículo"));

        buttonGroupPossueCarros.add(jCheckBox1Sim);
        jCheckBox1Sim.setText("Sim");
        jCheckBox1Sim.setEnabled(false);

        buttonGroupPossueCarros.add(jCheckBox1Nao);
        jCheckBox1Nao.setText("Não");
        jCheckBox1Nao.setEnabled(false);

        jTextFieldCarroMarca.setEditable(false);
        jTextFieldCarroMarca.setEnabled(false);

        jTextFieldCor.setEditable(false);
        jTextFieldCor.setEnabled(false);

        jTextFieldPlacas.setEditable(false);
        jTextFieldPlacas.setEnabled(false);

        jLabelCarroMarca.setText("Carro/ Car - Marca:");

        jLabelCarro.setText("Possue Carro?");

        jLabelPlacas.setText("Placas:");

        jLabelCor.setText("Cor:");

        javax.swing.GroupLayout jPanel1CarroLayout = new javax.swing.GroupLayout(jPanel1Carro);
        jPanel1Carro.setLayout(jPanel1CarroLayout);
        jPanel1CarroLayout.setHorizontalGroup(
            jPanel1CarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1CarroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCarro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox1Sim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox1Nao)
                .addGap(118, 118, 118)
                .addComponent(jLabelCarroMarca)
                .addGap(30, 30, 30)
                .addComponent(jTextFieldCarroMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCor, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPlacas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1CarroLayout.setVerticalGroup(
            jPanel1CarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1CarroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1CarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCarro)
                    .addComponent(jCheckBox1Sim)
                    .addComponent(jCheckBox1Nao)
                    .addComponent(jLabelCarroMarca)
                    .addComponent(jTextFieldCarroMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCor)
                    .addComponent(jTextFieldCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPlacas)
                    .addComponent(jTextFieldPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelTitulo.setFont(new java.awt.Font("Razer Header Regular", 1, 24)); // NOI18N
        jLabelTitulo.setText("Ficha de Registro - registration card");

        jComboBoxAptos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aptº 1", "Aptº 2", "Aptº 3", "Aptº 4" }));
        jComboBoxAptos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxAptosItemStateChanged(evt);
            }
        });

        jButtonCadastrarNovoCliente.setText("Cadastrar Novo Locatário");
        jButtonCadastrarNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarNovoClienteActionPerformed(evt);
            }
        });

        jLabelApto.setText("Aptº:");

        jButtonregistrarEntrada.setText("Registrar Entrada");
        jButtonregistrarEntrada.setActionCommand("");
        jButtonregistrarEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonregistrarEntradaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1DadosLocatario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonRetornarPrincipal)
                        .addGap(557, 557, 557)
                        .addComponent(jButtonregistrarEntrada)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRegistrarSaida))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonCadastrarNovoCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelApto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxAptos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelTitulo)
                    .addComponent(jPanel1Carro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelApto)
                    .addComponent(jComboBoxAptos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCadastrarNovoCliente))
                .addGap(7, 7, 7)
                .addComponent(jPanel1DadosLocatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1Carro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonRegistrarSaida)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonregistrarEntrada)
                        .addComponent(jButtonRetornarPrincipal)))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1075, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void limparCamposDepoisDeSalvar() {

        this.carregarComboApt();
        this.carregarComboCpfLocatario();
        
        Date datareg;
        datareg = Datas.obterTimestampAtual();
        String dataRegT = Datas.formatarData(datareg, "dd/MM/yyyy");
        jTextField1DataDeRegistro.setText(dataRegT);
        jTextFieldDataEntrada.setText(null);
        jTextFieldDataSaida.setText(null);
        
        //////////////////////////////////////////
        jTextFieldNomeCompleto.setText(null);
        jTextFieldEstCivil.setText(null);
        jTextFieldFone.setText(null);
        jTextFieldCelular.setText(null);
        jTextFieldIdade.setText(null);
        jTextFieldEnderecoRes.setText(null);
        jTextFieldAptN.setText(null);
        jTextFieldBairro.setText(null);
        jTextFieldCEP.setText(null);
        jTextFieldProcedencia.setText(null);
        jTextFieldMotivo.setText(null);
        jTextFieldEmail.setText(null);
        jTextFieldIdentidade.setText(null);
        jTextFieldOrgExp.setText(null);
        jTextFieldPassaport.setText(null);
        jTextFieldResponsavel.setText(null);
        jTextFieldCarroMarca.setText(null);
        jTextFieldCor.setText(null);
        jTextFieldPlacas.setText(null);

        //////////////////////////////////////////
        jCheckBox1Nao.setSelected(false);
        jCheckBox1Sim.setSelected(false);
        jCheckBox2Nao.setSelected(false);
        jCheckBox2Sim.setSelected(false);
        jCheckBox3Nao.setSelected(false);
        jCheckBox3Sim.setSelected(false);
        
        /////////////////////////////////////////
        
        jComboBoxAptos.setSelectedIndex(0);
        jComboBoxCPF.setSelectedIndex(0);
        jComboBoxFormaDePagamento.setSelectedIndex(0);
        
        jTextFieldValorDiaria.setText(null);
        jTextFieldValorMensal.setText(null);
        jTextFieldValorTotal.setText(null);
        jTextFieldLeituraEntrada.setText(null);
        jTextFieldLeituraSaida.setText(null);
        jTextFieldTotalKw.setText(null);

    }
    
    private void jButtonRetornarPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetornarPrincipalActionPerformed
        // TODO add your handling code here:
        tpp.setVisible(true);
        tpp.listarTabelaP();
        this.dispose();
    }//GEN-LAST:event_jButtonRetornarPrincipalActionPerformed

    private void jButtonCadastrarNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarNovoClienteActionPerformed
        // TODO add your handling code here:
        TelaNovoAlterarLocatario nLoc = new TelaNovoAlterarLocatario(this);
        this.setVisible(false);
        nLoc.setVisible(true);
    }//GEN-LAST:event_jButtonCadastrarNovoClienteActionPerformed

    private void jComboBoxCPFItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxCPFItemStateChanged
        // TODO add your handling code here:
        Fachada f = new Fachada();
        Locatario l;

        l = listaLocatario.get(jComboBoxCPF.getSelectedIndex());

        cpfSelecionado = f.findLocatario(l);

        jTextFieldNomeCompleto.setText(cpfSelecionado.getNome());
        jTextFieldEstCivil.setText(cpfSelecionado.getEstadocivil());
        jTextFieldFone.setText(cpfSelecionado.getTelefone());
        jTextFieldCelular.setText(cpfSelecionado.getTelefone2());
        jTextFieldIdade.setText(cpfSelecionado.getIdade() + "");
        jTextFieldEnderecoRes.setText(cpfSelecionado.getEndereco());
        jTextFieldAptN.setText(cpfSelecionado.getApto());
        jTextFieldBairro.setText(cpfSelecionado.getBairro());
        jTextFieldCEP.setText(cpfSelecionado.getCep());
        jTextFieldProcedencia.setText(cpfSelecionado.getProcedencia());
        jTextFieldMotivo.setText(cpfSelecionado.getMotivoviagem());
        jTextFieldEmail.setText(cpfSelecionado.getEmail());
        jTextFieldIdentidade.setText(cpfSelecionado.getIdentidade());
        jTextFieldOrgExp.setText(cpfSelecionado.getOrgexp());
        jTextFieldPassaport.setText(cpfSelecionado.getPassaporte());
        jTextFieldResponsavel.setText(cpfSelecionado.getResponsavelpagamento());
        jTextFieldCarroMarca.setText(cpfSelecionado.getCarro());
        jTextFieldCor.setText(cpfSelecionado.getCarrocor());
        jTextFieldPlacas.setText(cpfSelecionado.getPlaca());

        if (cpfSelecionado.getCarro() == null || cpfSelecionado.getCarro().trim().equals("")) {
            jCheckBox1Nao.setSelected(true);

        } else {
            jCheckBox1Sim.setSelected(true);
        }

    }//GEN-LAST:event_jComboBoxCPFItemStateChanged

    private void jComboBoxAptosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxAptosItemStateChanged
        // TODO add your handling code here:
        Fachada f = new Fachada();
        Apartamento a;

        a = listaApartamento.get(jComboBoxAptos.getSelectedIndex());

        aptSelecionado = f.findApartamento(a);
    }//GEN-LAST:event_jComboBoxAptosItemStateChanged

    private void jButtonregistrarEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonregistrarEntradaActionPerformed
        // TODO add your handling code here:
        try {
            Fachada fachada = new Fachada();
            CheckIn c = new CheckIn();

            c.setApartamento(aptSelecionado);
            c.setLocatario(cpfSelecionado);

            //datas
            c.setDataderegistro(Datas.criarData(jTextField1DataDeRegistro.getText()));

            c.setDataentrada(Datas.criarData(jTextFieldDataEntrada.getText()));
            c.setDatasaida(Datas.criarData(jTextFieldDataSaida.getText()));
            //////////////////////////////////////////////////////////////////////////

            //Valores
            Double valorMensal = Double.parseDouble(jTextFieldValorMensal.getText());
            c.setValormensal(valorMensal);

            Double valorDiaria = Double.parseDouble(jTextFieldValorDiaria.getText());
            c.setValordiaria(valorDiaria);

            Double valorTotal = Double.parseDouble(jTextFieldValorTotal.getText());

            c.setValortotaldiarias(valorTotal);
            ///////////////////////////////////////////////////////////////////////
            c.setFormaPagamento(jComboBoxFormaDePagamento.getSelectedItem().toString());

            c.setLeituraEntrada(jTextFieldLeituraEntrada.getText());
            c.setLeituraSaida(jTextFieldLeituraSaida.getText());
            c.setLeituraTotal(jTextFieldTotalKw.getText());

            //campos Booleanos de Leituras
            if (jCheckBox2Sim.isSelected()) {
                c.setAcompanhouLeituraEntrada(true);
            } else {
                c.setAcompanhouLeituraEntrada(false);
            }

            if (jCheckBox3Sim.isSelected()) {
                c.setAcompanhouLeituraSaida(true);
            } else {
                c.setAcompanhouLeituraSaida(false);
            }

            fachada.saveCheckIn(c);

            this.limparCamposDepoisDeSalvar();

        } catch (CheckInException x) {
            JOptionPane.showMessageDialog(rootPane, x);
        }
        JOptionPane.showMessageDialog(rootPane, "CheckIn Registrado com sucesso!");

    }//GEN-LAST:event_jButtonregistrarEntradaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciaCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciaCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciaCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciaCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGerenciaCheckIn().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1leituraEntrada;
    private javax.swing.ButtonGroup buttonGroup2leituraSaida;
    private javax.swing.ButtonGroup buttonGroupPossueCarros;
    private javax.swing.JButton jButtonCadastrarNovoCliente;
    private javax.swing.JButton jButtonRegistrarSaida;
    private javax.swing.JButton jButtonRetornarPrincipal;
    private javax.swing.JButton jButtonregistrarEntrada;
    private javax.swing.JCheckBox jCheckBox1Nao;
    private javax.swing.JCheckBox jCheckBox1Sim;
    private javax.swing.JCheckBox jCheckBox2Nao;
    private javax.swing.JCheckBox jCheckBox2Sim;
    private javax.swing.JCheckBox jCheckBox3Nao;
    private javax.swing.JCheckBox jCheckBox3Sim;
    private javax.swing.JComboBox jComboBoxAptos;
    private javax.swing.JComboBox jComboBoxCPF;
    private javax.swing.JComboBox jComboBoxFormaDePagamento;
    private javax.swing.JLabel jLabel1Acompanhou;
    private javax.swing.JLabel jLabel1DataRegistro;
    private javax.swing.JLabel jLabel2Acompanhou;
    private javax.swing.JLabel jLabelAptN;
    private javax.swing.JLabel jLabelApto;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelCEP;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelCarro;
    private javax.swing.JLabel jLabelCarroMarca;
    private javax.swing.JLabel jLabelCelular;
    private javax.swing.JLabel jLabelCor;
    private javax.swing.JLabel jLabelDataEntrada;
    private javax.swing.JLabel jLabelDataSaida;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEnderecoRes;
    private javax.swing.JLabel jLabelEstCivil;
    private javax.swing.JLabel jLabelFone;
    private javax.swing.JLabel jLabelFormaDePagamento;
    private javax.swing.JLabel jLabelIdade;
    private javax.swing.JLabel jLabelIdentidade;
    private javax.swing.JLabel jLabelLeituraEntrada;
    private javax.swing.JLabel jLabelLeituraSaida;
    private javax.swing.JLabel jLabelMotivo;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelOrgExp;
    private javax.swing.JLabel jLabelPassaport;
    private javax.swing.JLabel jLabelPlacas;
    private javax.swing.JLabel jLabelProcedencia;
    private javax.swing.JLabel jLabelResponsavel;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTotalKw;
    private javax.swing.JLabel jLabelValorDiaria;
    private javax.swing.JLabel jLabelValorMensal;
    private javax.swing.JLabel jLabelValorTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel1Carro;
    private javax.swing.JPanel jPanel1DadosLocatario;
    private javax.swing.JPanel jPanelDados;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1DataDeRegistro;
    private javax.swing.JTextField jTextFieldAptN;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCEP;
    private javax.swing.JTextField jTextFieldCarroMarca;
    private javax.swing.JTextField jTextFieldCelular;
    private javax.swing.JTextField jTextFieldCor;
    private javax.swing.JTextField jTextFieldDataEntrada;
    private javax.swing.JTextField jTextFieldDataSaida;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEnderecoRes;
    private javax.swing.JTextField jTextFieldEstCivil;
    private javax.swing.JTextField jTextFieldFone;
    private javax.swing.JTextField jTextFieldIdade;
    private javax.swing.JTextField jTextFieldIdentidade;
    private javax.swing.JTextField jTextFieldLeituraEntrada;
    private javax.swing.JTextField jTextFieldLeituraSaida;
    private javax.swing.JTextField jTextFieldMotivo;
    private javax.swing.JTextField jTextFieldNomeCompleto;
    private javax.swing.JTextField jTextFieldOrgExp;
    private javax.swing.JTextField jTextFieldPassaport;
    private javax.swing.JTextField jTextFieldPlacas;
    private javax.swing.JTextField jTextFieldProcedencia;
    private javax.swing.JTextField jTextFieldResponsavel;
    private javax.swing.JTextField jTextFieldTotalKw;
    private javax.swing.JTextField jTextFieldValorDiaria;
    private javax.swing.JTextField jTextFieldValorMensal;
    private javax.swing.JTextField jTextFieldValorTotal;
    // End of variables declaration//GEN-END:variables
}
