/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import classesbasicas.Locatario;
import classesbasicas.Login;
import classesexception.LocatarioException;
import classesfachada.Fachada;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import util.Datas;

/**
 *
 * @author SONY VAIO
 */
public class TelaNovoAlterarLocatario extends javax.swing.JFrame {

    /**
     * Creates new form NovoAlterarLocatario
     */
    Locatario locSelecionado = new Locatario();
    
   Login login;
    public TelaNovoAlterarLocatario(Login l) {
        initComponents();
        this.login = l;
        this.jButtonAlterar.setEnabled(false);
        //data de registro
        Date datareg;
        datareg = Datas.obterTimestampAtual();
        String dataRegT = Datas.formatarData(datareg, "dd/MM/yyyy");
        this.jTextFieldDataRegistro.setText(dataRegT);
        this.jTextFieldDataRegistro.setEnabled(false);
    }
    public TelaNovoAlterarLocatario(){
        
    }
    

    
    
    TelaNovoAlterarLocatario(Locatario loc, Login l) {
        initComponents();
        this.login = l;
        this.locSelecionado = loc;
        jTextFieldNome.setText(loc.getNome());
        jTextFieldEndereco.setText(loc.getEndereco());
        jTextFieldApto.setText(loc.getApto());
        jTextFieldNumero.setText(loc.getNumero());
        jTextFieldCidade.setText(loc.getCidade());
        jTextFieldBairro.setText(loc.getBairro());
        jTextFieldCep.setText(loc.getCep());
        jTextFieldIdade.setText(String.valueOf(loc.getIdade()));
        jTextFieldEstado.setText(loc.getEstado());
        jTextFieldProcedencia.setText(loc.getProcedencia());
        jTextFieldIdentidade.setText(loc.getIdentidade());
        jTextFieldOrgaoExp.setText(loc.getOrgexp());
        jTextFieldMotivo.setText(loc.getMotivoviagem());
        jTextFieldCpf.setText(loc.getCpf());
        jTextFieldEstadoCivil.setText(loc.getEstadocivil());
        jTextFieldCarro.setText(loc.getCarro());
        jTextFieldCor.setText(loc.getCarrocor());
        jTextFieldPlaca.setText(loc.getPlaca());

        jTextFieldDataRegistro.setText(Datas.formatarData(loc.getDataderegistro(), "dd/MM/yyyy"));

        jTextFieldFone.setText(loc.getTelefone());
        jTextFieldCelular.setText(loc.getTelefone2());
        jTextFieldEmail.setText(loc.getEmail());
        jTextFieldPassaporte.setText(loc.getPassaporte());
        jTextFieldResponsavelPag.setText(loc.getResponsavelpagamento());
        
        this.jButtonSalvar.setEnabled(false);
        this.jTextFieldDataRegistro.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelBarra = new javax.swing.JLabel();
        jPanelCadastroLocatario = new javax.swing.JPanel();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelEndereco = new javax.swing.JLabel();
        jTextFieldEndereco = new javax.swing.JTextField();
        jLabelApto = new javax.swing.JLabel();
        jTextFieldApto = new javax.swing.JTextField();
        jLabelBairro = new javax.swing.JLabel();
        jTextFieldBairro = new javax.swing.JTextField();
        jLabelCep = new javax.swing.JLabel();
        jTextFieldCep = new javax.swing.JTextField();
        try{  
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("#####-###");  
            jTextFieldCep = new javax.swing.JFormattedTextField(data);  
        }  
        catch (Exception e){  
        }
        jLabelFone = new javax.swing.JLabel();
        jTextFieldIdade = new javax.swing.JTextField();
        jLabelCelular = new javax.swing.JLabel();
        jTextFieldCelular = new javax.swing.JTextField();
        jLabelNumero = new javax.swing.JLabel();
        jTextFieldNumero = new javax.swing.JTextField();
        jLabelCidade = new javax.swing.JLabel();
        jTextFieldCidade = new javax.swing.JTextField();
        jLabelEstado = new javax.swing.JLabel();
        jLabelProcedencia = new javax.swing.JLabel();
        jLabelMotivo = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelIdentidade = new javax.swing.JLabel();
        jLabelOrgaoExp = new javax.swing.JLabel();
        jTextFieldEstado = new javax.swing.JTextField();
        jTextFieldProcedencia = new javax.swing.JTextField();
        jTextFieldIdentidade = new javax.swing.JTextField();
        jTextFieldMotivo = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldOrgaoExp = new javax.swing.JTextField();
        jTextFieldResponsavelPag = new javax.swing.JTextField();
        jLabelPassaporte = new javax.swing.JLabel();
        jLabelCpf = new javax.swing.JLabel();
        jLabelEstadoCivil = new javax.swing.JLabel();
        jLabelIdade = new javax.swing.JLabel();
        jLabelCarro = new javax.swing.JLabel();
        jLabelCor = new javax.swing.JLabel();
        jLabelPlaca = new javax.swing.JLabel();
        jLabelDataRegistro = new javax.swing.JLabel();
        jLabelResponsavelPag = new javax.swing.JLabel();
        jTextFieldCpf = new javax.swing.JTextField();
        try{  
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("###.###.###-##");  
            jTextFieldCpf = new javax.swing.JFormattedTextField(data);  
        }  
        catch (Exception e){  
        }
        jTextFieldEstadoCivil = new javax.swing.JTextField();
        jTextFieldFone = new javax.swing.JTextField();
        jTextFieldCarro = new javax.swing.JTextField();
        jTextFieldCor = new javax.swing.JTextField();
        jTextFieldPlaca = new javax.swing.JTextField();
        try{  
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("UUU-####");  
            jTextFieldPlaca = new javax.swing.JFormattedTextField(data);  
        }  
        catch (Exception e){  
        }
        jTextFieldPassaporte = new javax.swing.JTextField();
        jTextFieldDataRegistro = new javax.swing.JTextField();
        jButtonSalvar = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonRetornar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelBarra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/barra2.png"))); // NOI18N

        jPanelCadastroLocatario.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Locatário"));

        jLabelNome.setText("* Nome Completo/ Full name:");

        jLabelEndereco.setText("Endereço residencial/ Full adress:");

        jLabelApto.setText("Aptº:");

        jLabelBairro.setText("Bairro:");

        jLabelCep.setText("CEP:");

        jLabelFone.setText("* Fone/ Phone:");

        jLabelCelular.setText("Celular:");

        jLabelNumero.setText("Número:");

        jLabelCidade.setText("Cidade:");

        jLabelEstado.setText("Estado:");

        jLabelProcedencia.setText("Última Procedência:");

        jLabelMotivo.setText("Motivo da Viagem:");

        jLabelEmail.setText("* E-mail:");

        jLabelIdentidade.setText("Identidade:");

        jLabelOrgaoExp.setText("Orgão Exp:");

        jLabelPassaporte.setText("Passaporte:");

        jLabelCpf.setText("* CPF:");

        jLabelEstadoCivil.setText("Estado Civil:");

        jLabelIdade.setText("Idade:");

        jLabelCarro.setText("Carro:");

        jLabelCor.setText("Cor:");

        jLabelPlaca.setText("Placa:");

        jLabelDataRegistro.setText("Data Registro:");

        jLabelResponsavelPag.setText("Responsável Pelo Pagamento:");

        javax.swing.GroupLayout jPanelCadastroLocatarioLayout = new javax.swing.GroupLayout(jPanelCadastroLocatario);
        jPanelCadastroLocatario.setLayout(jPanelCadastroLocatarioLayout);
        jPanelCadastroLocatarioLayout.setHorizontalGroup(
            jPanelCadastroLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLocatarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastroLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelCadastroLocatarioLayout.createSequentialGroup()
                        .addComponent(jLabelResponsavelPag)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldResponsavelPag))
                    .addGroup(jPanelCadastroLocatarioLayout.createSequentialGroup()
                        .addGroup(jPanelCadastroLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelCadastroLocatarioLayout.createSequentialGroup()
                                .addComponent(jLabelMotivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelCadastroLocatarioLayout.createSequentialGroup()
                                .addGap(291, 291, 291)
                                .addComponent(jLabelPlaca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelCadastroLocatarioLayout.createSequentialGroup()
                                .addComponent(jLabelCarro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelCor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCor, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelCadastroLocatarioLayout.createSequentialGroup()
                                .addComponent(jLabelEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldEmail)))
                        .addGap(10, 10, 10)
                        .addGroup(jPanelCadastroLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadastroLocatarioLayout.createSequentialGroup()
                                .addComponent(jLabelCpf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelEstadoCivil)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldEstadoCivil))
                            .addGroup(jPanelCadastroLocatarioLayout.createSequentialGroup()
                                .addComponent(jLabelPassaporte)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPassaporte, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelDataRegistro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldDataRegistro))
                            .addGroup(jPanelCadastroLocatarioLayout.createSequentialGroup()
                                .addComponent(jLabelFone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldFone, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCelular)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCelular))))
                    .addGroup(jPanelCadastroLocatarioLayout.createSequentialGroup()
                        .addGroup(jPanelCadastroLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelCadastroLocatarioLayout.createSequentialGroup()
                                .addComponent(jLabelEstado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldEstado))
                            .addGroup(jPanelCadastroLocatarioLayout.createSequentialGroup()
                                .addComponent(jLabelApto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldApto, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(jPanelCadastroLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadastroLocatarioLayout.createSequentialGroup()
                                .addComponent(jLabelNumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(472, 472, 472))
                            .addGroup(jPanelCadastroLocatarioLayout.createSequentialGroup()
                                .addComponent(jLabelProcedencia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldProcedencia, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jLabelIdentidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIdentidade, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelCadastroLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelCadastroLocatarioLayout.createSequentialGroup()
                                .addComponent(jLabelIdade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelCadastroLocatarioLayout.createSequentialGroup()
                                .addComponent(jLabelOrgaoExp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldOrgaoExp, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))))
                    .addGroup(jPanelCadastroLocatarioLayout.createSequentialGroup()
                        .addComponent(jLabelNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNome))
                    .addGroup(jPanelCadastroLocatarioLayout.createSequentialGroup()
                        .addComponent(jLabelEndereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCadastroLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadastroLocatarioLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelCidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelBairro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jLabelCep)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextFieldEndereco))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCadastroLocatarioLayout.setVerticalGroup(
            jPanelCadastroLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLocatarioLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanelCadastroLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEndereco)
                    .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelIdade))
                    .addGroup(jPanelCadastroLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldApto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelApto)
                        .addComponent(jLabelNumero)
                        .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelCidade)
                        .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelBairro)
                        .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelCep)
                        .addComponent(jTextFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastroLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelEstado)
                        .addComponent(jTextFieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelProcedencia)
                        .addComponent(jTextFieldProcedencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCadastroLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelIdentidade)
                        .addComponent(jTextFieldIdentidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelOrgaoExp)
                        .addComponent(jTextFieldOrgaoExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(jPanelCadastroLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMotivo)
                    .addComponent(jLabelCpf)
                    .addComponent(jTextFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEstadoCivil)
                    .addComponent(jTextFieldEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFone)
                    .addComponent(jTextFieldFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCelular)
                    .addComponent(jTextFieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCarro)
                    .addComponent(jTextFieldCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCor)
                    .addComponent(jTextFieldCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPlaca)
                    .addComponent(jTextFieldPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPassaporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPassaporte)
                    .addComponent(jLabelDataRegistro)
                    .addComponent(jTextFieldDataRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEmail)
                    .addComponent(jTextFieldEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldResponsavelPag)
                    .addComponent(jLabelResponsavelPag))
                .addContainerGap())
        );

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonRetornar.setText("Retornar");
        jButtonRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetornarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCadastroLocatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonRetornar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabelBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPanelCadastroLocatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jButtonSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRetornar)
                        .addGap(39, 39, 39))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void limparCamposDepoisDeSalvar() {
        jTextFieldNome.setText(null);
        jTextFieldEndereco.setText(null);
        jTextFieldApto.setText(null);
        jTextFieldNumero.setText(null);
        jTextFieldCidade.setText(null);
        jTextFieldBairro.setText(null);
        jTextFieldCep.setText(null);
        jTextFieldIdade.setText(null);
        jTextFieldEstado.setText(null);
        jTextFieldProcedencia.setText(null);
        jTextFieldIdentidade.setText(null);
        jTextFieldOrgaoExp.setText(null);
        jTextFieldMotivo.setText(null);
        jTextFieldCpf.setText(null);
        jTextFieldEstadoCivil.setText(null);
        jTextFieldCarro.setText(null);
        jTextFieldCor.setText(null);
        jTextFieldPlaca.setText(null);
        
        jTextFieldDataRegistro.setText(null);
        
        jTextFieldFone.setText(null);
        jTextFieldCelular.setText(null);
        jTextFieldEmail.setText(null);
        jTextFieldPassaporte.setText(null);
        jTextFieldResponsavelPag.setText(null);

    }

    public void limparCamposDepoisDeAlterar() {
        jTextFieldNome.setText(null);
        jTextFieldEndereco.setText(null);
        jTextFieldApto.setText(null);
        jTextFieldNumero.setText(null);
        jTextFieldCidade.setText(null);
        jTextFieldBairro.setText(null);
        jTextFieldCep.setText(null);
        jTextFieldIdade.setText(null);
        jTextFieldEstado.setText(null);
        jTextFieldProcedencia.setText(null);
        jTextFieldIdentidade.setText(null);
        jTextFieldOrgaoExp.setText(null);
        jTextFieldMotivo.setText(null);
        jTextFieldCpf.setText(null);
        jTextFieldEstadoCivil.setText(null);
        jTextFieldCarro.setText(null);
        jTextFieldCor.setText(null);
        jTextFieldPlaca.setText(null);
        
        jTextFieldDataRegistro.setText(null);
        
        jTextFieldFone.setText(null);
        jTextFieldCelular.setText(null);
        jTextFieldEmail.setText(null);
        jTextFieldPassaporte.setText(null);
        jTextFieldResponsavelPag.setText(null);

        jButtonAlterar.setEnabled(false);

    }
    
    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:
        try {
            Fachada fachada = new Fachada();
            Locatario l = new Locatario();
            l.setNome(jTextFieldNome.getText());
            l.setEndereco(jTextFieldEndereco.getText());
            l.setApto(jTextFieldApto.getText());
            l.setNumero(jTextFieldNumero.getText());
            l.setCidade(jTextFieldCidade.getText());
            l.setBairro(jTextFieldBairro.getText());
            l.setCep(jTextFieldCep.getText());
            if(l.getCep().equals("     -   ")){
                l.setCep("");
            }
            l.setIdade(jTextFieldIdade.getText());
            l.setEstado(jTextFieldEstado.getText());
            l.setProcedencia(jTextFieldProcedencia.getText());
            l.setIdentidade(jTextFieldIdentidade.getText());
            l.setOrgexp(jTextFieldOrgaoExp.getText());
            l.setMotivoviagem(jTextFieldMotivo.getText());
            l.setCpf(jTextFieldCpf.getText());
            if(l.getCpf().equals("   .   .   -  ")){
                l.setCpf("");
            }
            l.setEstadocivil(jTextFieldEstadoCivil.getText());
            l.setCarro(jTextFieldCarro.getText());
           
            l.setCarrocor(jTextFieldCor.getText());
            l.setPlaca(jTextFieldPlaca.getText());
             if(l.getPlaca().equals("   -    ")){
               l.setPlaca("");
            }
            Date datareg = new Date();
            l.setDataderegistro(datareg);

            l.setTelefone(jTextFieldFone.getText());
            l.setTelefone2(jTextFieldCelular.getText());
            l.setEmail(jTextFieldEmail.getText());
            l.setPassaporte(jTextFieldPassaporte.getText());
            l.setResponsavelpagamento(jTextFieldResponsavelPag.getText());

            fachada.saveLocatario(l);
            
            this.limparCamposDepoisDeSalvar();
            JOptionPane.showMessageDialog(rootPane, "Locatário Salvo com sucesso!");
        } catch (LocatarioException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
        

    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetornarActionPerformed
        // TODO add your handling code here:
        TelaGerenciaLocatario tgl = new TelaGerenciaLocatario(login);
        tgl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonRetornarActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        // TODO add your handling code here:
        try {
            Fachada f = new Fachada();
            locSelecionado = f.findLocatario(locSelecionado);
            
            locSelecionado.setNome(jTextFieldNome.getText());
            locSelecionado.setEndereco(jTextFieldEndereco.getText());
            locSelecionado.setApto(jTextFieldApto.getText());
            locSelecionado.setNumero(jTextFieldNumero.getText());
            locSelecionado.setCidade(jTextFieldCidade.getText());
            locSelecionado.setBairro(jTextFieldBairro.getText());
            locSelecionado.setCep(jTextFieldCep.getText());
                  if(locSelecionado.getCep().equals("     -   ")){
                locSelecionado.setCep("");
            }
            locSelecionado.setIdade(jTextFieldIdade.getText());
            locSelecionado.setEstado(jTextFieldEstado.getText());
            locSelecionado.setProcedencia(jTextFieldProcedencia.getText());
            locSelecionado.setIdentidade(jTextFieldIdentidade.getText());
            locSelecionado.setOrgexp(jTextFieldOrgaoExp.getText());
            locSelecionado.setMotivoviagem(jTextFieldMotivo.getText());
            locSelecionado.setCpf(jTextFieldCpf.getText());
            locSelecionado.setEstadocivil(jTextFieldEstadoCivil.getText());
            locSelecionado.setCarro(jTextFieldCarro.getText());
             if(locSelecionado.getCarro().equals("   -    ")){
               locSelecionado.setCarro("");
            }
            locSelecionado.setCarrocor(jTextFieldCor.getText());
            locSelecionado.setPlaca(jTextFieldPlaca.getText());

            locSelecionado.setDataderegistro(Datas.criarData(jTextFieldDataRegistro.getText()));

            locSelecionado.setTelefone(jTextFieldFone.getText());
            locSelecionado.setTelefone2(jTextFieldCelular.getText());
            locSelecionado.setEmail(jTextFieldEmail.getText());
            locSelecionado.setPassaporte(jTextFieldPassaporte.getText());
            locSelecionado.setResponsavelpagamento(jTextFieldResponsavelPag.getText());
            
            f.saveLocatario(locSelecionado);
            this.limparCamposDepoisDeAlterar();

            JOptionPane.showMessageDialog(rootPane, "Locatário Alterado com sucesso!");
        } catch (LocatarioException ex) {
            Logger.getLogger(TelaNovoAlterarApt.class.getName()).log(Level.SEVERE, null, ex.getMessage());
        }
        
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaNovoAlterarLocatario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaNovoAlterarLocatario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaNovoAlterarLocatario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaNovoAlterarLocatario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaNovoAlterarLocatario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonRetornar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabelApto;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelBarra;
    private javax.swing.JLabel jLabelCarro;
    private javax.swing.JLabel jLabelCelular;
    private javax.swing.JLabel jLabelCep;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelCor;
    private javax.swing.JLabel jLabelCpf;
    private javax.swing.JLabel jLabelDataRegistro;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEndereco;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelEstadoCivil;
    private javax.swing.JLabel jLabelFone;
    private javax.swing.JLabel jLabelIdade;
    private javax.swing.JLabel jLabelIdentidade;
    private javax.swing.JLabel jLabelMotivo;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelOrgaoExp;
    private javax.swing.JLabel jLabelPassaporte;
    private javax.swing.JLabel jLabelPlaca;
    private javax.swing.JLabel jLabelProcedencia;
    private javax.swing.JLabel jLabelResponsavelPag;
    private javax.swing.JPanel jPanelCadastroLocatario;
    private javax.swing.JTextField jTextFieldApto;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCarro;
    private javax.swing.JTextField jTextFieldCelular;
    private javax.swing.JTextField jTextFieldCep;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldCor;
    private javax.swing.JTextField jTextFieldCpf;
    private javax.swing.JTextField jTextFieldDataRegistro;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldEstado;
    private javax.swing.JTextField jTextFieldEstadoCivil;
    private javax.swing.JTextField jTextFieldFone;
    private javax.swing.JTextField jTextFieldIdade;
    private javax.swing.JTextField jTextFieldIdentidade;
    private javax.swing.JTextField jTextFieldMotivo;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldOrgaoExp;
    private javax.swing.JTextField jTextFieldPassaporte;
    private javax.swing.JTextField jTextFieldPlaca;
    private javax.swing.JTextField jTextFieldProcedencia;
    private javax.swing.JTextField jTextFieldResponsavelPag;
    // End of variables declaration//GEN-END:variables
}
