/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import classesbasicas.CheckIn;
import classesbasicas.Login;
import classesfachada.Fachada;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mimmo 
 Qual a diferença entre Locatario e Locatário ? 
 Locatario é o proprietário do imóvel, geralmente representado por uma administradora.
 O locatário é o que aluga o imóvel para moradia ou uso comercial.
 */
public class TelaPainelPrincipal extends javax.swing.JFrame {

    Login login;
    CheckIn chekinSelecionado;
    
    public TelaPainelPrincipal(){
        
    }
    public TelaPainelPrincipal(Login login2) {
        initComponents();
        listarTabelaP();
        this.login = login2;
    }

    public void listarTabelaP() {

        Fachada f = new Fachada();
        CheckIn checkIn = new CheckIn();
        ArrayList<CheckIn> listaCheckIno;

        listaCheckIno = (ArrayList<CheckIn>) f.listallCheckIn(checkIn);

        DefaultTableModel dtm = new DefaultTableModel();
        dtm.setColumnIdentifiers(new String[]{"Id","Aptº", "Data Entrada",
            "Data Saída", "Locatario", "Situação"});
        for (int i = 0; i < listaCheckIno.size(); i++) {
            if(listaCheckIno.get(i).getDataCheckout()==null){
                    dtm.addRow(new String[]{listaCheckIno.get(i).getId() + "",
                    listaCheckIno.get(i).getApartamento().getNumero() + "",
                    listaCheckIno.get(i).getDataentrada() + "",
                    listaCheckIno.get(i).getDatasaida() + "",
                    listaCheckIno.get(i).getLocatario().getNome() + "",
                    listaCheckIno.get(i).getApartamento().getSituacao()
            
                            });
            }
        }

        jTablePrincipal.setModel(dtm);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelApt = new javax.swing.JLabel();
        jTextFieldApt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePrincipal = new javax.swing.JTable();
        jLabelNQuartos = new javax.swing.JLabel();
        jTextFieldNQuartos = new javax.swing.JTextField();
        jLabelSituacao = new javax.swing.JLabel();
        jTextFieldSituacao = new javax.swing.JTextField();
        jLabelVM = new javax.swing.JLabel();
        jLabelLocador = new javax.swing.JLabel();
        jTextFieldVM = new javax.swing.JTextField();
        jTextFieldLocador = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButtonCheckIn = new javax.swing.JButton();
        jButtonApt = new javax.swing.JButton();
        jButtonLocatario = new javax.swing.JButton();
        jButtonReservas = new javax.swing.JButton();
        jButtonProprietarios = new javax.swing.JButton();
        jButtonCheckIn1 = new javax.swing.JButton();
        jButtonProprietarios1 = new javax.swing.JButton();
        jButtonProprietarios2 = new javax.swing.JButton();
        jButtonReservas1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabelApt.setText("Aptº:");

        jTextFieldApt.setEditable(false);

        jTablePrincipal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Aptº", "Data Entrada", "Data Saída", "Possui Reservas", "Situação"
            }
        ));
        jTablePrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePrincipalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePrincipal);

        jLabelNQuartos.setText("Nº de Quartos:");

        jTextFieldNQuartos.setEditable(false);

        jLabelSituacao.setText("Situação:");

        jTextFieldSituacao.setEditable(false);

        jLabelVM.setText("Valor Mínimo:");

        jLabelLocador.setText("Locador:");

        jTextFieldVM.setEditable(false);

        jTextFieldLocador.setEditable(false);

        jButtonCheckIn.setText("Check In");
        jButtonCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCheckInActionPerformed(evt);
            }
        });

        jButtonApt.setText("Aptº");
        jButtonApt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAptActionPerformed(evt);
            }
        });

        jButtonLocatario.setText("Locatário");
        jButtonLocatario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLocatarioActionPerformed(evt);
            }
        });

        jButtonReservas.setText("Reservas");
        jButtonReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReservasActionPerformed(evt);
            }
        });

        jButtonProprietarios.setText("Proprietários");
        jButtonProprietarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProprietariosActionPerformed(evt);
            }
        });

        jButtonCheckIn1.setText("CheckOut");
        jButtonCheckIn1.setToolTipText("");
        jButtonCheckIn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCheckIn1ActionPerformed(evt);
            }
        });

        jButtonProprietarios1.setText("Sair");
        jButtonProprietarios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProprietarios1ActionPerformed(evt);
            }
        });

        jButtonProprietarios2.setText("Veiculos");
        jButtonProprietarios2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProprietarios2ActionPerformed(evt);
            }
        });

        jButtonReservas1.setText("Relatorios");
        jButtonReservas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReservas1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCheckIn, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                    .addComponent(jButtonCheckIn1, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                    .addComponent(jButtonProprietarios2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonApt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonReservas, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jButtonReservas1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonProprietarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonLocatario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonProprietarios1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCheckIn)
                    .addComponent(jButtonProprietarios)
                    .addComponent(jButtonApt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLocatario)
                    .addComponent(jButtonReservas)
                    .addComponent(jButtonCheckIn1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonProprietarios1)
                    .addComponent(jButtonProprietarios2)
                    .addComponent(jButtonReservas1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/barra2.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel1)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelApt)
                                .addGap(4, 4, 4)
                                .addComponent(jTextFieldApt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabelVM)
                                .addGap(4, 4, 4)
                                .addComponent(jTextFieldVM, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelNQuartos)
                                .addGap(10, 10, 10)
                                .addComponent(jTextFieldNQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelSituacao)
                                .addGap(10, 10, 10)
                                .addComponent(jTextFieldSituacao))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelLocador)
                                .addGap(10, 10, 10)
                                .addComponent(jTextFieldLocador)))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldApt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldVM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelApt)
                                    .addComponent(jLabelVM))))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNQuartos)
                                    .addComponent(jLabelSituacao))))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabelLocador))
                            .addComponent(jTextFieldLocador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(808, 384));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheckInActionPerformed
        // TODO add your handling code here:
        TelaGerenciaCheckIn tCheckIn = new TelaGerenciaCheckIn(login);
        this.setVisible(false);
        tCheckIn.setVisible(true);
    }//GEN-LAST:event_jButtonCheckInActionPerformed

    private void jButtonReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReservasActionPerformed
        // TODO add your handling code here:
        TelaGerenciaReserva tRes = new TelaGerenciaReserva(login);
        
        tRes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonReservasActionPerformed

    private void jButtonProprietariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProprietariosActionPerformed
        // TODO add your handling code here:
        TelaGerenciaProprietario tPro = new TelaGerenciaProprietario(login);
        this.setVisible(false);
        tPro.setVisible(true);
        
    }//GEN-LAST:event_jButtonProprietariosActionPerformed

    private void jButtonLocatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLocatarioActionPerformed
        // TODO add your handling code here:
        TelaGerenciaLocatario tLoc = new TelaGerenciaLocatario(login);
        
        tLoc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonLocatarioActionPerformed

    private void jButtonAptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAptActionPerformed
        // TODO add your handling code here:
        TelaGerenciaApt tApt = new TelaGerenciaApt(login);
        
        tApt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonAptActionPerformed

    private void jTablePrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePrincipalMouseClicked
        // TODO add your handling code here:
        Fachada f = new Fachada();
       CheckIn c = new CheckIn();

        int linha_selecionada = jTablePrincipal.getSelectedRow();
        c.setId(Integer.parseInt(jTablePrincipal.getValueAt(linha_selecionada, 0).toString()));

        chekinSelecionado = (f.findCheckIn(c));
       
        jTextFieldApt.setText(chekinSelecionado.getApartamento().getNumero() + "");
        jTextFieldVM.setText(chekinSelecionado.getApartamento().getValorminimo() + "");
        jTextFieldNQuartos.setText(chekinSelecionado.getApartamento().getQuartos() + "");
        jTextFieldSituacao.setText(chekinSelecionado.getApartamento().getSituacao());
        jTextFieldLocador.setText(chekinSelecionado.getApartamento().getProprietario().getNome());

    }//GEN-LAST:event_jTablePrincipalMouseClicked

    private void jButtonProprietarios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProprietarios1ActionPerformed
       this.dispose();
       System.exit(WIDTH);
    }//GEN-LAST:event_jButtonProprietarios1ActionPerformed

    private void jButtonCheckIn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheckIn1ActionPerformed
       if(chekinSelecionado!= null){
        TelaGerenciaCheckOut tela = new TelaGerenciaCheckOut(chekinSelecionado,login);
         tela.setVisible(true);
       this.dispose();}
       else{
           JOptionPane.showMessageDialog(rootPane,"Registro Não Selecionado");
       }
    }//GEN-LAST:event_jButtonCheckIn1ActionPerformed

    private void jButtonProprietarios2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProprietarios2ActionPerformed
       TelaGerenciarVeiculos tela = new TelaGerenciarVeiculos(login);
       tela.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButtonProprietarios2ActionPerformed

    private void jButtonReservas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReservas1ActionPerformed
        TelaRelatorios tela = new TelaRelatorios(login);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonReservas1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPainelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPainelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPainelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPainelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPainelPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonApt;
    private javax.swing.JButton jButtonCheckIn;
    private javax.swing.JButton jButtonCheckIn1;
    private javax.swing.JButton jButtonLocatario;
    private javax.swing.JButton jButtonProprietarios;
    private javax.swing.JButton jButtonProprietarios1;
    private javax.swing.JButton jButtonProprietarios2;
    private javax.swing.JButton jButtonReservas;
    private javax.swing.JButton jButtonReservas1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelApt;
    private javax.swing.JLabel jLabelLocador;
    private javax.swing.JLabel jLabelNQuartos;
    private javax.swing.JLabel jLabelSituacao;
    private javax.swing.JLabel jLabelVM;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePrincipal;
    private javax.swing.JTextField jTextFieldApt;
    private javax.swing.JTextField jTextFieldLocador;
    private javax.swing.JTextField jTextFieldNQuartos;
    private javax.swing.JTextField jTextFieldSituacao;
    private javax.swing.JTextField jTextFieldVM;
    // End of variables declaration//GEN-END:variables
}
