/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import classesbasicas.Locatario;
import classesfachada.Fachada;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import util.Datas;

/**
 *
 * @author mimmo
 */
public class TelaGerenciaLocatario extends javax.swing.JFrame {

    /**
     * Creates new form CadastroLocador
     */
    
    Locatario locSelecionado = new Locatario();
    
    public TelaGerenciaLocatario() {
        initComponents();
        
        listarTabelaLocatario();
        jButton2Alterar.setEnabled(false);
    }
    
    
    
    public void listarTabelaLocatario() {
        
        Fachada f = new Fachada();
        Locatario l = new Locatario();
        ArrayList<Locatario> listaLocatario;
        listaLocatario = (ArrayList<Locatario>) f.listallLocatario(l);
        
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.setColumnIdentifiers(new String[]{"Id", "Nome", "Fone",
            "Celular", "E-mail"});
        for (int i = 0; i < listaLocatario.size(); i++) {
            dtm.addRow(new String[]{listaLocatario.get(i).getId() + "",
                listaLocatario.get(i).getNome() + "",
                listaLocatario.get(i).getTelefone() + "",
                listaLocatario.get(i).getTelefone2() + "",
                listaLocatario.get(i).getEmail()
            });
        }
        
        jTableLocatario.setModel(dtm);
        
    }
    
    public void limparCampos() {
        jTextFieldNome.setText(null);
        jTextFieldEndereco.setText(null);
        jTextFieldApto.setText(null);
        jTextFieldNumero.setText(null);
        jTextFieldCidade.setText(null);
        jTextFieldBairro.setText(null);
        jTextFieldCep.setText(null);
        jTextFieldIdade.setText(null);
        jTextFieldEstado.setText(null);
        jTextFieldProcedencia.setText(null);
        jTextFieldIdentidade.setText(null);
        jTextFieldOrgaoExp.setText(null);
        jTextFieldMotivo.setText(null);
        jTextFieldCpf.setText(null);
        jTextFieldEstadoCivil.setText(null);
        jTextFieldCarro.setText(null);
        jTextFieldCor.setText(null);
        jTextFieldPlaca.setText(null);
        
        jTextFieldDataRegistro.setText(null);
        
        jTextFieldFone.setText(null);
        jTextFieldCelular.setText(null);
        jTextFieldEmail.setText(null);
        jTextFieldPassaporte.setText(null);
        jTextFieldResponsavelPag.setText(null);
        
        this.jButton2Alterar.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelBarra = new javax.swing.JLabel();
        jPanelCadastroLocatario = new javax.swing.JPanel();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelEndereco = new javax.swing.JLabel();
        jTextFieldEndereco = new javax.swing.JTextField();
        jLabelApto = new javax.swing.JLabel();
        jTextFieldApto = new javax.swing.JTextField();
        jLabelBairro = new javax.swing.JLabel();
        jTextFieldBairro = new javax.swing.JTextField();
        jLabelCep = new javax.swing.JLabel();
        jTextFieldCep = new javax.swing.JTextField();
        jLabelFone = new javax.swing.JLabel();
        jTextFieldIdade = new javax.swing.JTextField();
        jLabelCelular = new javax.swing.JLabel();
        jTextFieldCelular = new javax.swing.JTextField();
        jLabelNumero = new javax.swing.JLabel();
        jTextFieldNumero = new javax.swing.JTextField();
        jLabelCidade = new javax.swing.JLabel();
        jTextFieldCidade = new javax.swing.JTextField();
        jLabelEstado = new javax.swing.JLabel();
        jLabelProcedencia = new javax.swing.JLabel();
        jLabelMotivo = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelIdentidade = new javax.swing.JLabel();
        jLabelOrgaoExp = new javax.swing.JLabel();
        jTextFieldEstado = new javax.swing.JTextField();
        jTextFieldProcedencia = new javax.swing.JTextField();
        jTextFieldIdentidade = new javax.swing.JTextField();
        jTextFieldMotivo = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldOrgaoExp = new javax.swing.JTextField();
        jTextFieldResponsavelPag = new javax.swing.JTextField();
        jLabelPassaporte = new javax.swing.JLabel();
        jLabelCpf = new javax.swing.JLabel();
        jLabelEstadoCivil = new javax.swing.JLabel();
        jLabelIdade = new javax.swing.JLabel();
        jLabelCarro = new javax.swing.JLabel();
        jLabelCor = new javax.swing.JLabel();
        jLabelPlaca = new javax.swing.JLabel();
        jLabelDataRegistro = new javax.swing.JLabel();
        jLabelResponsavelPag = new javax.swing.JLabel();
        jTextFieldCpf = new javax.swing.JTextField();
        jTextFieldEstadoCivil = new javax.swing.JTextField();
        jTextFieldFone = new javax.swing.JTextField();
        jTextFieldCarro = new javax.swing.JTextField();
        jTextFieldCor = new javax.swing.JTextField();
        jTextFieldPlaca = new javax.swing.JTextField();
        jTextFieldPassaporte = new javax.swing.JTextField();
        jTextFieldDataRegistro = new javax.swing.JTextField();
        jLabelTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLocatario = new javax.swing.JTable();
        jButtonNovo = new javax.swing.JButton();
        jButton2Alterar = new javax.swing.JButton();
        jButton3Retornar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabelBarra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/barra2.png"))); // NOI18N

        jPanelCadastroLocatario.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Locatário"));

        jLabelNome.setText("Nome Completo/ Full name:");

        jTextFieldNome.setEditable(false);
        jTextFieldNome.setEnabled(false);

        jLabelEndereco.setText("Endereço residencial/ Full adress:");

        jTextFieldEndereco.setEditable(false);
        jTextFieldEndereco.setEnabled(false);

        jLabelApto.setText("Aptº:");

        jTextFieldApto.setEditable(false);
        jTextFieldApto.setEnabled(false);

        jLabelBairro.setText("Bairro:");

        jTextFieldBairro.setEditable(false);
        jTextFieldBairro.setEnabled(false);

        jLabelCep.setText("CEP:");

        jTextFieldCep.setEditable(false);
        jTextFieldCep.setEnabled(false);

        jLabelFone.setText("Fone/ Phone:");

        jTextFieldIdade.setEditable(false);
        jTextFieldIdade.setEnabled(false);

        jLabelCelular.setText("Celular:");

        jTextFieldCelular.setEditable(false);
        jTextFieldCelular.setEnabled(false);

        jLabelNumero.setText("Número:");

        jTextFieldNumero.setEditable(false);
        jTextFieldNumero.setEnabled(false);

        jLabelCidade.setText("Cidade:");

        jTextFieldCidade.setEditable(false);
        jTextFieldCidade.setEnabled(false);

        jLabelEstado.setText("Estado:");

        jLabelProcedencia.setText("Última Procedência:");

        jLabelMotivo.setText("Motivo da Viagem:");

        jLabelEmail.setText("E-mail:");

        jLabelIdentidade.setText("Identidade:");

        jLabelOrgaoExp.setText("Orgão Exp:");

        jTextFieldEstado.setEditable(false);
        jTextFieldEstado.setEnabled(false);

        jTextFieldProcedencia.setEditable(false);
        jTextFieldProcedencia.setEnabled(false);

        jTextFieldIdentidade.setEditable(false);
        jTextFieldIdentidade.setEnabled(false);

        jTextFieldMotivo.setEditable(false);
        jTextFieldMotivo.setEnabled(false);

        jTextFieldEmail.setEditable(false);
        jTextFieldEmail.setEnabled(false);

        jTextFieldOrgaoExp.setEditable(false);
        jTextFieldOrgaoExp.setEnabled(false);

        jTextFieldResponsavelPag.setEditable(false);
        jTextFieldResponsavelPag.setEnabled(false);

        jLabelPassaporte.setText("Passaporte:");

        jLabelCpf.setText("CPF:");

        jLabelEstadoCivil.setText("Estado Civil:");

        jLabelIdade.setText("Idade:");

        jLabelCarro.setText("Carro:");

        jLabelCor.setText("Cor:");

        jLabelPlaca.setText("Placa:");

        jLabelDataRegistro.setText("Data Registro:");

        jLabelResponsavelPag.setText("Responsável Pelo Pagamento:");

        jTextFieldCpf.setEditable(false);
        jTextFieldCpf.setEnabled(false);

        jTextFieldEstadoCivil.setEditable(false);
        jTextFieldEstadoCivil.setEnabled(false);

        jTextFieldFone.setEditable(false);
        jTextFieldFone.setEnabled(false);

        jTextFieldCarro.setEditable(false);
        jTextFieldCarro.setEnabled(false);

        jTextFieldCor.setEditable(false);
        jTextFieldCor.setEnabled(false);

        jTextFieldPlaca.setEditable(false);
        jTextFieldPlaca.setEnabled(false);

        jTextFieldPassaporte.setEditable(false);
        jTextFieldPassaporte.setEnabled(false);

        jTextFieldDataRegistro.setEditable(false);
        jTextFieldDataRegistro.setEnabled(false);

        javax.swing.GroupLayout jPanelCadastroLocatarioLayout = new javax.swing.GroupLayout(jPanelCadastroLocatario);
        jPanelCadastroLocatario.setLayout(jPanelCadastroLocatarioLayout);
        jPanelCadastroLocatarioLayout.setHorizontalGroup(
            jPanelCadastroLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLocatarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastroLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelCadastroLocatarioLayout.createSequentialGroup()
                        .addComponent(jLabelResponsavelPag)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldResponsavelPag))
                    .addGroup(jPanelCadastroLocatarioLayout.createSequentialGroup()
                        .addGroup(jPanelCadastroLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelCadastroLocatarioLayout.createSequentialGroup()
                                .addComponent(jLabelMotivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelCadastroLocatarioLayout.createSequentialGroup()
                                .addGap(291, 291, 291)
                                .addComponent(jLabelPlaca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelCadastroLocatarioLayout.createSequentialGroup()
                                .addComponent(jLabelCarro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelCor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCor, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelCadastroLocatarioLayout.createSequentialGroup()
                                .addComponent(jLabelEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldEmail)))
                        .addGap(10, 10, 10)
                        .addGroup(jPanelCadastroLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadastroLocatarioLayout.createSequentialGroup()
                                .addComponent(jLabelCpf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelEstadoCivil)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldEstadoCivil))
                            .addGroup(jPanelCadastroLocatarioLayout.createSequentialGroup()
                                .addComponent(jLabelPassaporte)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPassaporte, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelDataRegistro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldDataRegistro))
                            .addGroup(jPanelCadastroLocatarioLayout.createSequentialGroup()
                                .addComponent(jLabelFone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldFone, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCelular)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCelular))))
                    .addGroup(jPanelCadastroLocatarioLayout.createSequentialGroup()
                        .addGroup(jPanelCadastroLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelCadastroLocatarioLayout.createSequentialGroup()
                                .addComponent(jLabelEstado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldEstado))
                            .addGroup(jPanelCadastroLocatarioLayout.createSequentialGroup()
                                .addComponent(jLabelApto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldApto, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCadastroLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelCadastroLocatarioLayout.createSequentialGroup()
                                .addComponent(jLabelNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelBairro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldBairro))
                            .addGroup(jPanelCadastroLocatarioLayout.createSequentialGroup()
                                .addComponent(jLabelProcedencia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldProcedencia, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(jPanelCadastroLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadastroLocatarioLayout.createSequentialGroup()
                                .addComponent(jLabelCep)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelCadastroLocatarioLayout.createSequentialGroup()
                                .addComponent(jLabelIdentidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldIdentidade, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelCadastroLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelCadastroLocatarioLayout.createSequentialGroup()
                                .addComponent(jLabelIdade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelCadastroLocatarioLayout.createSequentialGroup()
                                .addComponent(jLabelOrgaoExp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldOrgaoExp, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))))
                    .addGroup(jPanelCadastroLocatarioLayout.createSequentialGroup()
                        .addComponent(jLabelEndereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldEndereco))
                    .addGroup(jPanelCadastroLocatarioLayout.createSequentialGroup()
                        .addComponent(jLabelNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNome)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCadastroLocatarioLayout.setVerticalGroup(
            jPanelCadastroLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLocatarioLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanelCadastroLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEndereco)
                    .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelBairro)
                        .addComponent(jLabelCep)
                        .addComponent(jTextFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelIdade))
                    .addGroup(jPanelCadastroLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldApto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelNumero)
                        .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelCidade)
                        .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelApto)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastroLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelEstado)
                        .addComponent(jTextFieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelProcedencia)
                        .addComponent(jTextFieldProcedencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCadastroLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelIdentidade)
                        .addComponent(jTextFieldIdentidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelOrgaoExp)
                        .addComponent(jTextFieldOrgaoExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(jPanelCadastroLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMotivo)
                    .addComponent(jLabelCpf)
                    .addComponent(jTextFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEstadoCivil)
                    .addComponent(jTextFieldEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFone)
                    .addComponent(jTextFieldFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCelular)
                    .addComponent(jTextFieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCarro)
                    .addComponent(jTextFieldCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCor)
                    .addComponent(jTextFieldCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPlaca)
                    .addComponent(jTextFieldPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPassaporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPassaporte)
                    .addComponent(jLabelDataRegistro)
                    .addComponent(jTextFieldDataRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEmail)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroLocatarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldResponsavelPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelResponsavelPag))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelTitulo.setFont(new java.awt.Font("Razer Header Regular", 1, 24)); // NOI18N
        jLabelTitulo.setText("Gerência Locatário");

        jTableLocatario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Título 1", "Título 2", "Título 3", "Título 4"
            }
        ));
        jTableLocatario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLocatarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableLocatario);

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButton2Alterar.setText("Alterar");
        jButton2Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2AlterarActionPerformed(evt);
            }
        });

        jButton3Retornar.setText("Retornar");
        jButton3Retornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3RetornarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBarra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTitulo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelCadastroLocatario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3Retornar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2Alterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTitulo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelCadastroLocatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButtonNovo)
                        .addGap(16, 16, 16)
                        .addComponent(jButton2Alterar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3Retornar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        // TODO add your handling code here:
        TelaNovoAlterarLocatario nLoc = new TelaNovoAlterarLocatario(this);
        this.setVisible(false);
        nLoc.setVisible(true);
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButton3RetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3RetornarActionPerformed
        // TODO add your handling code here:
        TelaPainelPrincipal tpp = new TelaPainelPrincipal();
        tpp.setVisible(true);
        tpp.listarTabelaP();
        this.dispose();
    }//GEN-LAST:event_jButton3RetornarActionPerformed

    private void jButton2AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2AlterarActionPerformed
        // TODO add your handling code here:
        TelaNovoAlterarLocatario nLoc = new TelaNovoAlterarLocatario(locSelecionado, this);
        this.setVisible(false);
        nLoc.setVisible(true);
    }//GEN-LAST:event_jButton2AlterarActionPerformed

    private void jTableLocatarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLocatarioMouseClicked
        // TODO add your handling code here:
        
        Fachada fachada = new Fachada();
        Locatario l = new Locatario();
        
        int linha_selecionada = jTableLocatario.getSelectedRow();
        l.setId(Integer.parseInt(jTableLocatario.getValueAt(linha_selecionada, 0).toString()));
        
        locSelecionado = (fachada.findLocatario(l));
        
        jTextFieldNome.setText(locSelecionado.getNome());
        jTextFieldEndereco.setText(locSelecionado.getEndereco());
        jTextFieldApto.setText(locSelecionado.getApto());
        jTextFieldNumero.setText(locSelecionado.getNumero());
        jTextFieldCidade.setText(locSelecionado.getCidade());
        jTextFieldBairro.setText(locSelecionado.getBairro());
        jTextFieldCep.setText(locSelecionado.getCep());
        jTextFieldIdade.setText(String.valueOf(locSelecionado.getIdade()));
        jTextFieldEstado.setText(locSelecionado.getEstado());
        jTextFieldProcedencia.setText(locSelecionado.getProcedencia());
        jTextFieldIdentidade.setText(locSelecionado.getIdentidade());
        jTextFieldOrgaoExp.setText(locSelecionado.getOrgexp());
        jTextFieldMotivo.setText(locSelecionado.getMotivoviagem());
        jTextFieldCpf.setText(locSelecionado.getCpg());
        jTextFieldEstadoCivil.setText(locSelecionado.getEstadocivil());
        jTextFieldCarro.setText(locSelecionado.getCarro());
        jTextFieldCor.setText(locSelecionado.getCarrocor());
        jTextFieldPlaca.setText(locSelecionado.getPlaca());
        jTextFieldFone.setText(locSelecionado.getTelefone());
        jTextFieldCelular.setText(locSelecionado.getTelefone2());
        jTextFieldEmail.setText(locSelecionado.getEmail());
        jTextFieldPassaporte.setText(locSelecionado.getPassaporte());
        jTextFieldDataRegistro.setText(Datas.formatarData(locSelecionado.getDataderegistro(), "dd/MM/yyyy"));
        jTextFieldResponsavelPag.setText(locSelecionado.getResponsavelpagamento());
        
        this.jButton2Alterar.setEnabled(true);
    }//GEN-LAST:event_jTableLocatarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciaLocatario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciaLocatario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciaLocatario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciaLocatario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGerenciaLocatario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2Alterar;
    private javax.swing.JButton jButton3Retornar;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JLabel jLabelApto;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelBarra;
    private javax.swing.JLabel jLabelCarro;
    private javax.swing.JLabel jLabelCelular;
    private javax.swing.JLabel jLabelCep;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelCor;
    private javax.swing.JLabel jLabelCpf;
    private javax.swing.JLabel jLabelDataRegistro;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEndereco;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelEstadoCivil;
    private javax.swing.JLabel jLabelFone;
    private javax.swing.JLabel jLabelIdade;
    private javax.swing.JLabel jLabelIdentidade;
    private javax.swing.JLabel jLabelMotivo;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelOrgaoExp;
    private javax.swing.JLabel jLabelPassaporte;
    private javax.swing.JLabel jLabelPlaca;
    private javax.swing.JLabel jLabelProcedencia;
    private javax.swing.JLabel jLabelResponsavelPag;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelCadastroLocatario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLocatario;
    private javax.swing.JTextField jTextFieldApto;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCarro;
    private javax.swing.JTextField jTextFieldCelular;
    private javax.swing.JTextField jTextFieldCep;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldCor;
    private javax.swing.JTextField jTextFieldCpf;
    private javax.swing.JTextField jTextFieldDataRegistro;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldEstado;
    private javax.swing.JTextField jTextFieldEstadoCivil;
    private javax.swing.JTextField jTextFieldFone;
    private javax.swing.JTextField jTextFieldIdade;
    private javax.swing.JTextField jTextFieldIdentidade;
    private javax.swing.JTextField jTextFieldMotivo;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldOrgaoExp;
    private javax.swing.JTextField jTextFieldPassaporte;
    private javax.swing.JTextField jTextFieldPlaca;
    private javax.swing.JTextField jTextFieldProcedencia;
    private javax.swing.JTextField jTextFieldResponsavelPag;
    // End of variables declaration//GEN-END:variables
}
